import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import { FaFacebookF, FaLinkedin, FaTwitter, FaGithub } from 'react-icons/fa'
import Link from 'next/link'
import Projects from '../components/Projects'
import Header from '../components/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>George Igboanugo - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="lg:h-full">
        <Header />
        <div className="grid grid-cols-1 lg:grid-cols-[100px_minmax(900px,_1fr)_100px] items-center lg:h-full">
          <div className="menu-links hidden lg:block">
            <ul className="menu rounded-box">
              <li>
                <a href='#hero'>
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
                </a>
              </li>
              <li>
                <a href='#projects'>
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                </a>
              </li>
              <li>
                <a>
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>
                </a>
              </li>
            </ul> 
          </div>
            <div className="lg:h-screen lg:overflow-y-scroll py-7" id="content">
              <section id="hero" className='lg:h-[88vh] h-screen flex lg:flex justify-center items-center'>
                <Hero />
              </section>
              <section id="projects" className='lg:h-[88vh] h-screen flex lg:flex justify-center items-center'>
                <Projects />
              </section>         
          </div>
          <div className="socials">
            <ul className="menu bg-none p-2 rounded-box">
              <li>
                <Link href="https://www.facebook.com/georgeigboanugo"><FaFacebookF className='text-2xl' /></Link>
              </li>
              <li>
                <Link href="https://www.linkedin.com/george.igboanugo"><FaLinkedin className='text-2xl' /></Link>
              </li>
              <li>
                <Link href="https://www.twitter.com/igeorge"><FaTwitter className='text-2xl' /></Link>
              </li>
              <li>
                <Link href="https://www.github.com/igeorge"><FaGithub className='text-2xl' /></Link>
              </li>              
            </ul>            
          </div>          
        </div>
      </main>

    </>
  )
}
