import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import { FaFacebookF, FaLinkedin, FaTwitter, FaGithub, FaHome, FaFolder, FaSchool } from 'react-icons/fa'
import Link from 'next/link'
import Projects from '../components/Projects'
import Header from '../components/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>George Igboanugo - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="lg:h-full">
        <Header />
        <div className="grid grid-cols-1 lg:grid-cols-[100px_minmax(900px,_1fr)_100px] items-center lg:h-full">
          <div className="menu-links hidden lg:block">
            <ul className="menu rounded-box">
              <li>
                <Link href='#hero'><FaHome /></Link>
              </li>
              <li>
                <Link href='#projects'><FaFolder /> </Link>
              </li>
              <li>
                <Link href="/"><FaSchool /></Link>
              </li>
            </ul> 
          </div>
            <div className="lg:h-screen lg:overflow-y-scroll py-7" id="content">
              <section id="hero" className='lg:h-[88vh] h-screen flex lg:flex justify-center items-center'>
                <Hero />
              </section>
              <section id="projects" className='lg:h-[88vh] h-screen flex lg:flex justify-center items-center'>
                <Projects />
              </section>         
          </div>
          <div className="socials">
            <ul className="menu bg-ghost rounded-box">
              <li>
                <Link href="https://www.facebook.com/georgeigboanugo"><FaFacebookF className='text-2xl' /></Link>
              </li>
              <li>
                <Link href="https://www.linkedin.com/george.igboanugo"><FaLinkedin className='text-2xl' /></Link>
              </li>
              <li>
                <Link href="https://www.twitter.com/igeorge"><FaTwitter className='text-2xl' /></Link>
              </li>
              <li>
                <Link href="https://www.github.com/igeorge"><FaGithub className='text-2xl' /></Link>
              </li>              
            </ul>            
          </div>          
        </div>
      </main>

    </>
  )
}
